Day4
amrendra-rathore/express-server pull request #4
Opened 2022-06-23 09:07 UTC by amrendra-rathore

## Task 1
Create a file validation.js inside the utils folder.

Define a variable 'users' of the following format.

[
{
traineeEmail: 'trainee1@successive.tech',
reviewerEmail: 'reviewer1@successive.tech',
}
]

Create a function validateEmail with the following:
- Accepts email as an argument.
- Uses a regex to validate the email and a specific domain.
- Return true if an email is correct otherwise false.

Create a function 'validateUsers' with the following:
- Accepts above-defined users as an argument.
- Iterate over the array of users.
- Validate traineeEmail and reviewerEmail using above-defined function.
- Prints all valid users with their count.
- Prints all invalid users with their count.

Acceptance Criteria:
- Should print correct no of valid and invalid users.
- Should use array methods to iterate over an array.
- Should use destructuring for fetching object properties.

## Task 2

Create a file permissions.js inside the utils folder.

Define variable named permissions in the following format:

{
'getUsers': {
all: ['head-trainer'],
read : ['trainee', 'trainer'],
write : ['trainer'],
delete: [],
}
}

Create a function named hasPermission with following:

Parameters: - moduleName i.e 'getUsers',
- role i.e 'trainee',
- permissionType i.e 'read', 'write' or 'delete' etc.

Output: Return true or false based on the parameters passed by checking in the module name, role, and permission type from the permissions object.
Proper logging inside functions.

2022-06-24 07:09 UTC, mohit-nx requested changes

2022-06-24 07:09 UTC, mohit-nx commented on utils/permissions.js
> +
print false if the module doesn't exists

2022-06-24 07:09 UTC, mohit-nx commented on utils/validation.js
> +  users.map((x) => {
use forEach

2022-06-24 09:18 UTC, amrendra-rathore commented on utils/permissions.js
> +
Added another if-else statement to check if the module exists.

2022-06-24 09:19 UTC, amrendra-rathore commented on utils/validation.js
> +  users.map((x) => {
used forEach instead of map.

2022-06-27 16:51 UTC, mohit-nx approved these changes

2022-06-27 16:51 UTC, merged