Day7
amrendra-rathore/express-server pull request #7
Opened 2022-06-28 13:30 UTC by amrendra-rathore

### Task Description:

Define .env file with following properties:

PORT=9000
NODE_ENV=dev

Create a folder src

Create a file Server.ts inside src

Define a class with the following methods and properties:

- config: property, It will be set by constructor from parameter received.
- bootstrap: call different methods needed for bootstrapping of app.
It will call setupRoutes for now.
It will return this.
- setupRoutes: Method to setup routes
We will define a route(of type get) '/health-check' which will return 'I am OK' as response.
- run: Method to run the express app.
Log error in case of error
Log success message in case of success.
It will return this.

Export Server class.

Create a folder config inside src
- Create a file IConfig.ts which contains interface of config (properties like port and env)
- Create a file configuration.ts
Use dotenv module for extracting config from .env file.
Define config using interface(IConfig).
Use Object.freeze for protecting config object against any modifications after the declaration.
Export config.

Create a file index.ts
Import config and Server.
Create an instance of Server by passing config in constructor
Call methods bootstrap and run using instance
App should be running and success message.

2022-07-01 12:38 UTC, divyansh0777 requested changes

2022-07-01 12:38 UTC, divyansh0777 commented on .env
> +NPDE_ENV=dev
Do not push .env file into GitHub. For reference create .env.example file with blank values and push it to GitHub.

2022-07-01 12:38 UTC, divyansh0777 commented on package.json
> +    "lint:fix": "./node_modules/tslint/bin/tslint --fix -c tslint.json -p tsconfig.json --exclude 'node_modules/**/*.{j,t}s'",
linting command is not correct. Refer docs

2022-07-01 12:38 UTC, divyansh0777 commented on package.json
> +    "express": "^4.18.1",
remove all carrot signs ^

2022-07-01 12:38 UTC, divyansh0777 commented on src/Server.ts
> +    this.app.get("/health-check", function(req , res)  {
Use arrow functions instead of basic JS function syntax

2022-07-01 12:38 UTC, divyansh0777 commented on src/config/IConfig.ts
> +  nodeEnv: any;
Do not use any. Use string instead

2022-07-01 12:38 UTC, divyansh0777 commented on src/config/configuration.ts
> +  port: Number(process.env.PORT)
Use parseInt function, this will increase complexity bus Number is a class

2022-07-01 12:38 UTC, divyansh0777 commented on src/index.ts
> +let server = new Server(configurations);
Do not use let, use const instead

2022-07-04 05:55 UTC, amrendra-rathore commented on src/Server.ts
> +    this.app.get("/health-check", function(req , res)  {
used arrow function instead of basic javascript function.

2022-07-04 05:56 UTC, amrendra-rathore commented on src/config/IConfig.ts
> +  nodeEnv: any;
Used string instead of any

2022-07-04 06:00 UTC, amrendra-rathore commented on src/index.ts
> +let server = new Server(configurations);
Used Const instead of let.

2022-07-04 06:00 UTC, amrendra-rathore commented on package.json
> +    "express": "^4.18.1",
Removed all carrot signs (^)

2022-07-04 06:01 UTC, amrendra-rathore commented on .env
> +NPDE_ENV=dev
Removed .env file and created a sample file named .env.example

2022-07-04 09:33 UTC, amrendra-rathore commented on package.json
> +    "lint:fix": "./node_modules/tslint/bin/tslint --fix -c tslint.json -p tsconfig.json --exclude 'node_modules/**/*.{j,t}s'",
fixed commands/scripts for linting issues.

2022-07-04 09:33 UTC, amrendra-rathore commented on src/config/configuration.ts
> +  port: Number(process.env.PORT)
Used parseInt() instead of Number class.

2022-07-04 09:39 UTC, merged